---
- hosts: localhost
  tasks:
  - group:
      name: testgrp
      state: present 
  - user:
      name: "{{ item }}"
      state: present
      groups: "testgrp"
    with_sequence: start=1 end=9 format=testuser%02x
